#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Plotting Class Definition
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#' @title PlotClass
#' @description A class to store plots generated by the CytoCrunch package
#' @slot runID A character string to identify the run
#' @slot plotType A character string to identify the type of plot
#' @slot plotObject An object of any type that represents the plot
#' @slot description An optional character string to store metadata or a description of the plot
#' @export
#' @examples
#' plotObj <- createPlotClass(runID = "testRun", plotType = "scatter")
#' plotObj
setClass(
  "PlotClass",
  slots = list(
    runID = "character",
    plotType = "character",
    plotObject = "ANY",     # Store any type of plot (ggplot, base R plot, etc.)
    description = "character" # Optional description or metadata
  )
)
#' Constructor for PlotClass
createPlotClass <- function(runID, plotType, plotObject = NULL) {
  new("PlotClass", runID = runID, plotType = plotType, plotObject = plotObject)
}
